language: python
before_install:
- mkdir -p ~/.config/earthengine/
- echo $GEE > ~/.config/earthengine/credentials
- sudo apt-get install openssl
- wget http://bit.ly/miniconda -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda update --yes conda
- travis_retry conda create --yes -n TEST $CONDA --file requirements.txt
- source activate TEST
- travis_retry conda install --yes -c conda-forge google-api-python-client
- travis_retry conda install --yes -c conda-forge earthengine-api
- travis_retry conda install --yes pytest
script:
- py.test --verbose --ignore setup.py
env:
  global:
    secure: aXlRMhqGZdvWNjJl4Cgz67+8i8iQiZEp1o6SIJoLf9uT8h8sMxH/YjAHHAGAAUVdmuD5uktjhzTfpFPr5gkQOkgFLDj1zla8L3j5/xXsMZBNS2E2cPhBMYAd/CDz2zg064LdbUYGXcawPHOfdgO0XNN2W+B63zDQjXvGI/c9qVOqc2ANojzr8AAUVt6pha56t6gMmkxHjUkuN20AcsZTF2KaJy42k4IsvOgYNw3B+fyHVffKbMXOVRVyz5fyLjIE1ggk6j9QSEIv0NGNPlJTRLb+Jm5p/cS3FcCd58E9owVBIbbpXq+xxmDyhGD70BB3GdQlK/yAwMDlM/9zyEj0WK/YFLAqCkiKcn+RzZs43A0iNJFhpYMonylwgkknDc9Qa4O35jUIajdv/zQRwvqb2t2UVZo1rREWLZHTtZezmcfxd6isM9IjeZ/k7Bu4ij7FCrPCA7MDMl4bSB0ns9l7eyH4+bl5jUtp2bLqfV8lWcXZGqtOr0YPo3JJAUB7sx602LDQ66IeZOvgvRIEXUMUeiaWEdyVMATSzr4GWegTqysJKPOTyyPYj6grTmDfTMOiDnTgvmsDSW7wIgx7z88fdEXDJkCeS1HE7Kh5KbO/w3Pojvz9xtxVj+BnG/c0jf85YQ7X0PioBfWSSGudWGvhRtAnhjfAvX10jWl1mSN6JPs=
